language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  exclude:
    - php: 5.3
      env: TYPO3_VERSION="^7.6.0"
    - php: 5.4
      env: TYPO3_VERSION="^7.6.0"
    - php: 5.3
      env: TYPO3_VERSION="dev-master"
    - php: 5.4
      env: TYPO3_VERSION="dev-master"
    - php: 5.5
      env: TYPO3_VERSION="dev-master"
    - php: 5.6
      env: TYPO3_VERSION="dev-master"
    - php: 7
      env: TYPO3_VERSION="^6.2.0"

env:
  global:
    - EXTENSIONKEY=piwikintegration
  matrix:
    - TYPO3_VERSION="^6.2.0"
    - TYPO3_VERSION="^7.6.0"
    - TYPO3_VERSION="dev-master"

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - composer --version
  - npm install csslint
  - npm -g install jshint
  - composer self-update


before_script:
  - composer require typo3/cms="$TYPO3_VERSION"
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web
  
script:
  - >
    ./bin/phpcs --standard=TYPO3CMS -n typo3conf/ext/$EXTENSIONKEY/Classes/
  - >
    echo;
    echo "Running css lint";
    /bin/bash -c "
      if [ -d typo3conf/ext/$EXTENSIONKEY/Resources/Public/Css/ ]; then
        csslint typo3conf/ext/$EXTENSIONKEY/Resources/Public/Css/
      fi
    "
  - >
    echo;
    echo "Running jshint";
    /bin/bash -c "
      if [ -d typo3conf/ext/$EXTENSIONKEY/Resources/Public/JavaScript/ ]; then
        jshint typo3conf/ext/$EXTENSIONKEY/Resources/Public/JavaScript/
      fi
    "
    - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/UnitTests.xml Tests/Unit/
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - >
    echo;
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit --colors  -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/FunctionalTests.xml {}'
